on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCIR_REPOSITORY: ${{ secrets.OCIR_REPOSITORY }}
      OCIR_ENDPOINT: ${{ secrets.OCIR_ENDPOINT }}
      OCIR_USERNAME: ${{ secrets.OCIR_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Enable ARM64 Architecture
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "arm64,arm"

      - name: Login to Oracle Cloud Infrastructure Registry (OCIR)
        id: login-oci
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Create env file
        run: |
          touch .env
          echo [env name]=${{ secrets.[secret name] }} >> .env
          cat .env

      - name: Build, Tag, Push the Docker Image
        id: build-image
        run: |
          docker build --platform arm64 -t $OCIR_ENDPOINT/$OCIR_USERNAME/$OCIR_REPOSITORY:latest-dev -f Dockerfile.development .
          docker push $OCIR_ENDPOINT/$OCIR_USERNAME/$OCIR_REPOSITORY:latest-dev

      - name: Deploy to OCI Compute Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd ${{ secrets.OCI_COMPOSE_DIRECTORY }}
            docker pull ${{ secrets.OCIR_ENDPOINT }}/${{ secrets.OCIR_USERNAME }}/${{ secrets.OCIR_REPOSITORY }}:latest-dev
            sh deploy-dev.sh